### ISSUE TITLE
Missing process ID protection !

### ISSUE THREAD

**Issue by wmBolles** [pickled-git/minitalk#1]
## Try to run the following test
```
./client 4294967295 test
```

### In this case, the pid value will be overflowed to -1 and SIGUSR1 and SIGUSR2 will be sent to all system processes and kill them
like : ./client -1 test

## To protect this case add the following condition in your code: 

```c
server_pid = ft_atoi(argv[1]);
	if (server_pid <= 0 || server_pid > 99998)
		exit(EXIT_FAILURE);
``` 
### The 99998 is the maximum number of processes that can open in mac machine.
Good project & Good luck

**Comment by oprosvir** [comment]
Thank you for pointing this out.
