### ISSUE TITLE
Makefile relink Problem !

### ISSUE THREAD

**Issue by wmBolles** [pickled-git/minitalk#2]
## If you make a change in your header file "minitalk.h" and try to make the Makefile again nothing change
because you have relink in your makefile
## To protect the Make file relink you need to add the header path in the dependencies of the pattern rule
```c
$(LIBFT):
	$(MAKE) -C $(LIBFT_PATH)

src/%.o: src/%.c include/minitalk.h #here
	$(CC) $(CFLAGS) -I$(INCLUDE) -I$(LIBFT_INCLUDE) -c $< -o $@

```
##In this case, if you make changes in your header file and make again, the makefile will compile all the c files into your code base
Good luck !

**Comment by oprosvir** [comment]
Hi,

You're definitely right, thank you. I will keep this in mind for future projects.
